  version: '3.8'

  services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        influxdb:
          condition: service_healthy
      environment:
        - INFLUXDB_URL=http://influxdb:8086
        - INFLUXDB_TOKEN=your-super-secret-auth-token
        - INFLUXDB_ORG=myorg
        - INFLUXDB_BUCKET=rules
        - SERVER_PORT=8080
      networks:
        - app-network
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 40s

    influxdb:
      image: influxdb:2.7
      ports:
        - "8086:8086"
      volumes:
        - influxdb_data:/var/lib/influxdb2
      environment:
        - DOCKER_INFLUXDB_INIT_MODE=setup
        - DOCKER_INFLUXDB_INIT_USERNAME=admin
        - DOCKER_INFLUXDB_INIT_PASSWORD=password123
        - DOCKER_INFLUXDB_INIT_ORG=myorg
        - DOCKER_INFLUXDB_INIT_BUCKET=rules
        - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=your-super-secret-auth-token
      networks:
        - app-network
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 40s

    test:
      build:
        context: .
        dockerfile: Dockerfile  # You can use the same Dockerfile for tests
      depends_on:
        - influxdb
      environment:
        - INFLUXDB_URL=http://influxdb:8086
        - INFLUXDB_TOKEN=your-super-secret-auth-token
        - INFLUXDB_ORG=myorg
        - INFLUXDB_BUCKET=rules
      networks:
        - app-network

  volumes:
    influxdb_data:

  networks:
    app-network:
      driver: bridge
