version: '3'

tasks:
  # Combined task to build the Docker images, start the application, and run tests
  setup:
    desc: "Setup: Build, Start, and Run Tests"
    cmds:
      - docker-compose up --build --abort-on-container-exit --remove-orphans
    silent: true

  # Stop and remove all containers, networks, and volumes
  down:
    desc: "Stop and remove all containers"
    cmds:
      - docker-compose down --volumes
